.github/workflows/crates.yml, .gitignore, Cargo.lock, Cargo.toml, SECURITY.md, benches/store_bench.rs, release.toml, src/lib.rs, src/storage/cache/s3fifo.rs, src/storage/index/mod.rs, src/storage/index/node.rs, src/storage/kv/entry.rs, src/storage/kv/error.rs, src/storage/kv/mod.rs, src/storage/kv/oracle.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs, src/storage/kv/util.rs, src/storage/log/mod.rs, src/storage/mod.rs
This PR introduces asynchronous functionality to the Store. The primary changes include:
- Make transaction commit async
- Refactored the Store to support async operations.
- Make test cases async
The main design change is that the store now pushes the writes to an async channel, and a background thread is consuming it and committing to the append-only log.
Looking into the usage of async aware lock(s).
=> Make store async

Cargo.toml
This pull request addresses a failing build by adding the sync module to tokio. Details of the failing build can be found [here](https://github.com/surrealdb/surrealkv/actions/runs/7829877141/job/21362732469) failing build.
=> add sync module for tokio

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, Makefile, src/storage/log/aof/log.rs, src/storage/log/mod.rs, src/storage/log/wal/log.rs
The nightly builds on sdb [fails](https://github.com/surrealdb/surrealdb/actions/runs/7935647669/job/21669276247) because some of the functions used to open/access file rely on unix crate exclusively. This PR adds support for windows systems as well.
=> fix: add windows file system support

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/storage/kv/store.rs, src/storage/log/aof/log.rs, src/storage/log/mod.rs
When the same file handler is being used, once a read happens, the cursor needs to be set to the end of file before appending again to avoid override.
=> fix: reset cursor to eof on append

src/storage/kv/error.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
This PR does the following:
1) Add a test for checking if store reloads after n restarts for durability check on restarts
2) Block reads on write-only transaction
=> chore: block reads on write-only txn and add store restart test

src/storage/kv/store.rs
This test case ensures that once data is added to skv, upon each reopening, it can successfully read the data and then append to it accordingly without any errors.
=> fix: close_reopen test should read inserted data and append in next run

src/storage/kv/entry.rs, src/storage/kv/store.rs
The `store.close()` method is async so it can't be directly called from `fn drop()`.
This PR introduces a Store wrapper that handles the drop asynchronously.
There's the caveat that if the Store is dropped and then we immediately try to open it again, the original store may not be closed yet.
In order to overcome that, the user can explicitly close the store instead of relying on the drop.
The drop is mainly intended to handle the common scenario where the Store is dropped when the program exits.
=> [store] Close the store asynchronously when it's dropped

src/storage/kv/oracle.rs, src/storage/kv/transaction.rs, src/storage/log/mod.rs
This PR addresses the [issue](https://github.com/surrealdb/surrealkv/issues/28) regarding write skews during range reads when using SSI mode for isolation
=> fix: track range bounds to detect write skew during range reads for SSI

Cargo.lock, Cargo.toml
Update the version of Vart to resolve the sorting issue in Node4 and release an SKV fix.
=> chore: update vart version to v0.2.1

Cargo.lock, Cargo.toml
This PR upgrades the skv version to 0.1.6, and includes the change to keep the store completely in memory
=> chore: update skv to 0.1.6

Cargo.lock, Cargo.toml, src/lib.rs, src/storage/kv/entry.rs, src/storage/kv/option.rs, src/storage/kv/oracle.rs, src/storage/kv/repair.rs, src/storage/kv/store.rs
This PR adds the ability for skv to act as a pure in-memory store. This can be used as alternative to other in-memory stores whilst testing inside sdb
=> feat: add option to store db in memory

Cargo.lock, Cargo.toml, src/storage/kv/compaction.rs, src/storage/kv/entry.rs, src/storage/kv/meta.rs, src/storage/kv/mod.rs, src/storage/kv/snapshot.rs, src/storage/kv/stats.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
Updates surrealkv version to 0.2.1, which includes the addition of the [`clear`](https://github.com/surrealdb/surrealkv/pull/47) method on a transaction
=> Chore/release 0.2.1

Cargo.lock, Cargo.toml, README.md, src/lib.rs, src/storage/kv/compaction.rs, src/storage/kv/entry.rs, src/storage/kv/error.rs, src/storage/kv/indexer.rs, src/storage/kv/meta.rs, src/storage/kv/oracle.rs, src/storage/kv/snapshot.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs, src/storage/kv/util.rs
This PR does the following:
1) Updates vart
2) Adds the following versioned APIs to the snapshot and tree
- `get_at_ts` (to get a key at a particular timestamp)
- `get_all_versions` (to get all the versions of a key)
- `scan_at_ts` (scans all keys at a timestamp)
- `keys_at_ts` (query all keys at a timestamp)
3) Add `get_value_by_query` to both tree and snapshot to query the value by the following query types
- `LatestByVersion`
- `LatestByTs`
- `LastLessThanTs`
- `LastLessOrEqualTs`
- `FirstGreaterThanTs`
- `FirstGreaterOrEqualTs`
=> chore: add methods to get keys at specific timestamps

Cargo.lock, Cargo.toml, benches/store_bench.rs
Fix panic in `store_bench`:
```
$ RUST_BACKTRACE=1 cargo bench --bench store_bench
Compiling surrealkv v0.3.0 (/Users/sergii/p/surrealkv)
Finished `bench` profile [optimized] target(s) in 1.18s
Running benches/store_bench.rs (target/release/deps/store_bench-edb8cc5dfa51a46c)
Gnuplot not found, using plotters backend
bulk load key/value lengths 10/0
time:   [15.518 µs 15.674 µs 15.863 µs]
change: [-3.1581% -1.7065% -0.3082%] (p = 0.02 < 0.05)
Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) low mild
1 (1.00%) high severe
thread 'main' panicked at src/storage/kv/store.rs:199:13:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
0: _rust_begin_unwind
1: core::panicking::panic_fmt
2: …
```
=> Fix panic in store_bench

Cargo.lock, Cargo.toml, benches/collection_bench.rs, src/storage/cache/s3fifo.rs, src/storage/kv/entry.rs, src/storage/kv/meta.rs, src/storage/kv/oracle.rs, src/storage/kv/reader.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs, src/storage/log/mod.rs
- Make transaction's `write_set` a vector of entries instead of a vector of tuples, since entry already contains key.
- On commit, extract the `write_set` with `mem::take()` instead of cloning.
- Use `HashMap::entry()` instead of a sequence of `get/insert` when checking if the key already exists in `write_order_map`.
- Remove the `Records` struct which was merely an intermediate vector of `Record`s for the encoding of entries.
- Replace `hashbrown` with `ahash`.
=> Reduce allocations and lookups in the write path

src/storage/kv/repair.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs, src/storage/log/aol.rs, src/storage/log/mod.rs
The `Weak` durability level is not really useful for our use case and can be removed. With it gone, there's no need in buffering writes either, since each record must be fully written into the segment's file descriptor and flushed to the OS buffers. This makes the write path simpler, and also reduces memory usage and copying.
What this PR does:
- Removes `Weak` durability level.
- Removes `Block` struct.
- Removes `flush()` methods because each record is flushed to the OS buffers by default.
- Uses `FileExt::read_at()` where available instead of seeking to and then reading the record.
Tested locally with surrealdb using `cargo make ci-api-integration-surrealkv`.
The block buffering is still used when loading the segments; this will be addressed in a follow-up PR.
=> Remove block buffering from the write path

src/storage/kv/manifest.rs, src/storage/kv/reader.rs, src/storage/kv/repair.rs, src/storage/kv/store.rs, src/storage/log/aol.rs, src/storage/log/mod.rs
`MultiSegmentReader` already uses `BufReader` for buffering file reads in memory, therefore there's no need for `Reader` to also buffer reads manually with `Vec<u8>`, and all of the associated code and copying.
Tested locally with surrealdb using `cargo make ci-api-integration-surrealkv`.
=> Remove extra read buffering

Cargo.lock, Cargo.toml, src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs
- Resolve values and truncate keys in `scan_at_ts`
- Make `scan_at_ts` available in read-write transactions
- Truncate keys in `keys_at`
- Bump the package version
=> fix: resolve values in scan_at_ts

Cargo.lock, Cargo.toml, src/storage/kv/transaction.rs
This change is needed for versioned queries.
=> Make get_at_ts available in read-write transactions

Cargo.lock, Cargo.toml, src/storage/kv/entry.rs, src/storage/kv/snapshot.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
By default SKV sets the records' timestamp locally at commit time. Make it possible to override the timestamp using `set_at_ts`. This change is needed for CREATE with VERSION in SurrealDB.
- Implement `set_at_ts()`.
- Remove `commit_ts` and do not pass it around.
- Fix the signature of `get_at_ts()`.
- Bump the version.
=> Implement set_at_ts

Cargo.lock, Cargo.toml, src/storage/kv/error.rs, src/storage/kv/oracle.rs, src/storage/kv/transaction.rs
- The API is modelled after RocksDB. `set_savepoint` is used to specify the state of a transaction to rollback to. `rollback_to_savepoint` is used to rollback to the latest savepoint.
- The savepoints are stackable. It's possible to set multiple savepoints within the same transaction and then rollback to each of them with the corresponding number of calls to `rollback_to_savepoint`.
- The implementation is quite simple. Each transaction stores the number of savepoints as `u32` with zero meaning none. When an entry is added to the transaction's write set, read set and scan set, its savepoint number is set to the current number of the transaction. In other words the entries are marked with the number of current savepoint. A call to `rollback_to_savepoint` merely removes all entries in the …
=> Implement savepoints

Cargo.lock, Cargo.toml, src/storage/kv/oracle.rs, src/storage/kv/transaction.rs, src/storage/kv/util.rs
Fixes https://github.com/surrealdb/surrealkv/issues/76.
- Make `write_set` a map from keys to a vec of value versions, each for a different savepoint. That way we could keep the values across savepoints and properly rollback to a previous version by re-adding it to the snapshot.
- ~~Making `write_set` a map also allowed me to get rid of `write_order_map` which has not been used anyway, meaning that we do not care about the order.~~ With it, we can also get rid of the expensive `sha256` calculations for keys, and also remove `sha2` as a dependency.
(Update) The order of writes within a transaction is now preserved with per-transaction sequence numbers.
- In `Transaction::get`, the write set is now checked first, before attempting the snapshot.
- Clean up `Transaction` by removing unused …
=> Savepoint rollback on an updated key should roll it back to previous version

src/storage/kv/oracle.rs, src/storage/kv/snapshot.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
`Snapshot::start_ts` is confusing because it can lead to using `now()` for getting the value which is clearly wrong. 
It's actually not used at all, since the snapshot object implicitly records the version/timestamp as the largest version stored in the root node.
Tested with SurrealDB.
=> Snapshots do not need start_ts

benches/store_bench.rs, src/storage/kv/compaction.rs, src/storage/kv/entry.rs, src/storage/kv/oracle.rs, src/storage/kv/repair.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
Using a mutex seems to be too big of a price for `Transaction::get` with immutable `&self`.  We are already using mutable transactions everywhere, so there is no loss of functionality here.
Tested with SurrealDB.
=> Read set and key ranges do not need mutex

src/storage/kv/compaction.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
This PR renames the delete/clear method to hard_delete and soft_delete.
`hard_delete`: will remove the key (and it's versions) from the index, and disk upon compaction.
`soft_delete`: will not remove the key (and it's versions) from the index, and disk upon compaction. It will just mark it as hidden.
=> chore: rename delete/clear to hard/soft delete

src/storage/kv/option.rs
Minor renaming of function on deprecated field in options for revision
=> chore: fix deprecated field revision func naming

Cargo.lock, Cargo.toml, src/storage/kv/indexer.rs, src/storage/kv/option.rs, src/storage/kv/store.rs
Uses https://github.com/surrealdb/vart/pull/57
Add a new configuration flag to control whether versions are enabled or disabled. The default is enabled.
Tested with SurrealDB using `cargo make ci-api-integration-surrealkv` with versions and disk persistence disabled.
=> Add a flag to disable versions

Cargo.lock, Cargo.toml, src/storage/kv/indexer.rs, src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs
Fixes a bug where scan after a hard_delete would create a read conflict. This is because snapshots created were always based on the vart version, which rolls back (or decreases) when a hard_delete occurs.
=> fix: sdb bug on hard delete and reinsert

src/storage/kv/transaction.rs
This PR modifies `scan_all_versions` API to apply limit on unique set of keys and not number of records. This is to avoid reading partial versions and not being able to read the remaining
=> Fix: scan all versions limit should be restricted to unique keys

src/storage/kv/snapshot.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
It's a utility method, high level logic like `Store::begin()` should take care of checking wether the store is open or closed.
=> Make store::read_ts() infallible

Cargo.lock, Cargo.toml, src/storage/kv/error.rs, src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs
This PR adds the following:
1) Adds check if the snapshot is not lesser than index version
2) Modifies Transaction::commit to return (tx_id, commit_ts) for verification
3) Add basic test to verify if concurrent transactions committed have incremental txn ids
Addresses https://github.com/surrealdb/surrealkv/issues/108
=> chore: add test for concurrent inserts

src/storage/kv/reader.rs, src/storage/kv/store.rs
Avoid using hashmap for checking value offset when reloading index
=> chore: avoid hashmap during index reload for offset

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/storage/kv/store.rs
Previously, when a Store was dropped without being explicitly closed (especially during program shutdown),
it could fail with "no reactor running" errors. This change gracefully falls back to creating a temporary runtime if necessary
=> chore: handle close when runtime is dropped

src/storage/kv/indexer.rs, src/storage/kv/store.rs
Since all writes are already serialized via the oracle and the task channel, there's actually no need to hold the index write lock while updating it because there can be no other concurrent transactions updating the index at the same time.
It's sufficient to clone it using the cheaper read lock, make all the modifications, and then update it as a whole at once. This is sorta RCU thanks to the copy-on-write vart tree. This should help parallel readers to experience less contention when starting transactions.
As a follow-up, we could probably take it even further by getting rid of the RWLock completely and use atomic pointer swap instead, for example the `arc-swap` crate.
Tested with SurrealDB.
=> Do not hold write lock while updating the index

.github/workflows/ci.yml, .github/workflows/crates.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, benches/store_bench.rs, src/storage/kv/store.rs
Fixes the issue for wasm spawn. There is no dependency on JoinHandle so that the task runner can be spawned using tokio or wasm-bindgen
=> Fix: Wasm spawn 

Cargo.lock, Cargo.toml, src/storage/kv/store.rs
This PR is a follow-up to https://github.com/surrealdb/surrealkv/pull/134.
When versions are disabled, `Transaction::soft_delete` should act as `Transaction::delete` and completely remove 
values from the index. Same should happen when loading up the index with versions disabled.
=> Make soft_delete completely remove values when replace is set

Cargo.lock, Cargo.toml, src/storage/kv/compaction.rs, src/storage/kv/indexer.rs, src/storage/kv/oracle.rs, src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs, src/storage/kv/util.rs
This integrates https://github.com/surrealdb/vart/pull/69
Will need to update `Cargo.toml` once the `vart` PR is merged.
=> Allow keys without zero byte terminator

src/storage/kv/compaction.rs, src/storage/kv/repair.rs, src/storage/kv/transaction.rs
Just a small cleanup:
- Use `HashSet` with `ahash`.
- I don't think there's need to insert a key in the unique keys set when processing the last key's versions.
- Fixing clippy lints for Rust 1.83.0.
=> Use ahash::HashSet

src/storage/kv/store.rs
Fixes the concurrency test where both tasks set the same key, leading to conflict in a multi threaded env
=> fix: set unique keys on concurrency test

src/storage/kv/transaction.rs
Internal versions are a part of the MVCC mechanism and should not be exposed.
=> Do not expose internal versions in scan

src/storage/kv/indexer.rs, src/storage/kv/oracle.rs, src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs
- Make snapshot's get and scan methods responsible for hiding the deleted keys.
- Remove the filters and their associated logic. We might bring them back in the future if we ever have more complicated conditions.
- Simplify some of the snapshot methods to use `Option` instead of `Result`, because not finding a key is not a failure.
Tested with SurrealDB.
=> Make snapshot fully responsible for the visibility of keys

src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs, src/storage/kv/util.rs
- Do not store writes in both the snapshot and the write set. Storing them is definitely convenient, because then all kinds of gets and scans become very easy to implement. Unfortunately, this convenience comes at a great cost, both in CPU and memory, because the writes to CoW Vart tree are expensive. Our benchmarks have demonstrated about 20% reduction in memory usage and speed of inserts. 
- Change `scan()`, `scan_at_ts()` and `get_at_ts()` to consider both the write set and the snapshot of a transaction. For the scans, the actual complexity is implemented in a new helper method `merging_scan`.
- Since our improved Snapshot Isolation does not need to track reads anymore, this PR also disables storing reads and scans by default, thus saving even more memory.
@arriqaaq I think we need to …
=> Do not store writes in the snapshot

src/snapshot.rs, src/transaction.rs
This PR does the following
1. Add `keys` function with signature (&self, range, limit)
2. Modify keys_at_ts with a limit argument, with signature (&self, range, ts, limit)
3. Modify keys_with_tombstones function with a limit argument, with signature (&self, range, limit)
=> feat: add keys api

src/snapshot.rs, src/store.rs, src/transaction.rs
This PR renames a bunch of APIs:
- get_at_version (get_at_ts)
- get_all_versions (get_history)
- scan_at_version (scan_at_ts)
- keys_at_version (keys_at_ts)
=> chore: change api names

Cargo.lock, Cargo.toml, benches/store_bench.rs, src/compaction.rs, src/iter.rs, src/lib.rs, src/oracle.rs, src/snapshot.rs, src/store.rs, src/transaction.rs
This PR does the following:
1. Updates vart and modifies changes required inside skv
2. Makes scan related APIs return iterator
=> Make Scan APIs return Iterator

benches/store_bench.rs
Also considerably reduce time of the concurrent inserts bench.
=> Enable concurrent benches

src/log/aol.rs, src/log/mod.rs
- The `Aol` is already thread safe due to `RwLock` at the `Store` level.
- Concurrent reads are safe because of `FileExt::read_at` which does not change the file descriptor's cursor.
- For the non-Unix platforms that do not provide `read_at`, use a conditional `Mutex` within the `Segment` object.
- Use `Mutex` instead of `RwLock` to protect the fd cache.
=> Move Aol mutex to Segment and make it conditional

cli/src/analyzer.rs, src/compaction.rs, src/log/aol.rs, src/log/fd.rs, src/log/mod.rs, src/manifest.rs, src/reader.rs, src/repair.rs, src/store.rs
This makes the aol read and write path completely independent of each other, without requiring any common locks
=> make aol read write path independent of common locks

src/compaction.rs, src/oracle.rs, src/store.rs, src/transaction.rs
- No `Arc` means no atomic increments and decrements for every commit due to `Arc::clone()`.
- The `Oracle` lock is moved to `Core` where it belongs.
- Make `Oracle`'s isolation methods accept immutable `&Transaction` instead of `&mut Transaction`.
=> No need to put Oracle into Arc

src/store.rs, src/util.rs
Set the weighter in quick cache to be based on value size so that the cache can be set in terms of space and not number of elements.
=> set value based weighter

src/store.rs
Reuse values from entries instead of cloning into a separate vector
=> Avoid cloning values during write cache

src/log/mod.rs
This PR adds fsync when opening the latest segment file, ensuring that any writes made before a crash are safely persisted. If a user process crashes after writing to the latest segment but before calling fsync, the page cache in the kernel will retain those writes. The next process to open the latest segment will access this cached data, immediately calling fsync to persist it to disk.
=> fsync on segment reopen

Cargo.toml, src/transaction.rs
This PR clears the transaction snapshot prior to commit. Since there is no dependency on the transaction snapshot during the commit phase, this could help have less references in vart to certain nodes.
=> Remove dependency on snapshot during commit

src/compaction.rs
This PR fixes a compaction failure on Windows caused by open file handles preventing the rename operation. Explicitly dropping temp_writer and manifest before the rename ensures the resources are freed, allowing the compaction process to complete successfully. Additionally, verified that all compaction tests now pass on Windows.
Fixes #194
=> Fix compaction on Windows by ensuring file handles are released before renaming
