src/storage/index/node.rs
The children nodes can be stored as `Option<Arc<N>>` instead of `MaybeUninit<Option<Arc<N>>`.
This way we get rid of unnecessary usage of unsafe when trying to access nodes.
I believe `MaybeUninit` was initially used because it wasn't straightforward to initialize a fixed length array of children. It is now being initialized like this:
```rust
let children: [Option<Arc<N>>; WIDTH] = std::array::from_fn(|_| None);
```
=> Remove unneeded usage of MaybeUninit

src/storage/kv/transaction.rs
This PR fixes the deletion bug in the store due to deletion of keys from snapshot before committing it and adds tests to verify the behavior of transactions when keys are deleted and then scanned. 
The test first creates a key-value pair in a read-write transaction, then deletes the key in a read-only transaction and scans the range where the key was located. The test asserts that the scan does not return the deleted key.
=> fix: do not delete key from snapshot until committed

src/storage/kv/store.rs
Fixes an issue where calling close twice on the store would result in an error.
=> fix: handle calling close on closed store

Cargo.lock, Cargo.toml
Bumps the version of skv to 0.1.4
=> chore: update crate to v0.1.4

Cargo.lock, Cargo.toml, src/storage/kv/oracle.rs
Removes unused crossbeam dependency
=> chore: remove unused dependencies

Cargo.lock, Cargo.toml, src/storage/kv/snapshot.rs
This PR updates vart version, which includes range scan optimization
=> chore: update vart to 0.4.1

Cargo.lock, Cargo.toml, src/storage/kv/indexer.rs, src/storage/kv/store.rs
Bring in https://github.com/surrealdb/vart/pull/48
=> Use Tree::insert instead of bulk_insert

src/storage/kv/oracle.rs
Wasm build on surrealdb fails because async_channel recv_blocking is not present for wasm builds. This PR provides a fix for it by blocking on the recv channel
=> fix: wasm build for async

Cargo.lock, Cargo.toml, src/storage/kv/indexer.rs, src/storage/kv/oracle.rs, src/storage/kv/snapshot.rs, src/storage/kv/transaction.rs
=> Cloned Tree is a snapshot

.github/workflows/release.yml, Cargo.lock, Cargo.toml
=> chore: update skv version to 0.5.0

.github/workflows/bench.yml, Cargo.lock, Cargo.toml, benches/store_bench.rs
Adding benchmarks to help detect perf differences
=> chore: improve benchmarks

src/storage/kv/transaction.rs
Returns all existing keys within the specified range, including soft-deleted and thus hidden by tombstones.
This is needed for the `REMOVE WITH EXPUNGE` functionality to work properly in SurrealDB. Without this change soft-deleted keys and their values will not be removed.
Let me know if another name is a better choice for this method. Maybe `all_index_keys()`?
=> Implement Transaction::keys_with_tombstones

Cargo.lock, src/storage/kv/error.rs, src/storage/kv/oracle.rs, src/storage/kv/store.rs, src/storage/kv/transaction.rs
Reverts surrealdb/surrealkv#132
=> Revert "Snapshot isolation and SSI rewrite"

src/iter.rs, src/store.rs, src/transaction.rs
Implements an iterator for scan_all_versions
=> Iterator for scan_all_versions

README.md
Fixes the readme to reflect the new changes with iter in scan
=> Fix scan op in Readme

src/oracle.rs
The current range validation logic has an exception that allows transactions to commit when they delete keys that were modified after the transaction's read timestamp. I can't think of any reason why this check needs to be there (or why I placed it there initially).
This PR removes the special deletion case and fails any transaction that encounters modifications to its read ranges that occurred after its read timestamp.
=> Fix potential write skew anomaly in SSI range validation

Cargo.lock, Cargo.toml
=> update vart to 0.9.1

src/compaction.rs, src/repair.rs, src/store.rs
=> Aol is already thread-safe, no need for another lock

benches/store_bench.rs, src/entry.rs, src/option.rs, src/store.rs, src/transaction.rs
Add option to enable cache on write
=> Add option to enable cache on write

benches/store_bench.rs, src/option.rs, src/store.rs
I don't see any benefit in having this write through cache given the reads are now non blocking.
=> Remove write through cache

src/indexer.rs, src/store.rs
Bringing back https://github.com/surrealdb/surrealkv/pull/129
=> Do not hold write lock while updating the index

src/iter.rs
This just cleans up a common pattern.
=> Add a type alias for items yielded by the snapshot iterator: SnapItem

src/batch.rs, src/bplustree/tree.rs, src/commit.rs, src/lsm.rs, src/memtable/mod.rs, src/transaction.rs, src/vlog.rs, src/wal/recovery.rs, src/wal/tests.rs
Allow writes to vlog before writing to wal or memtable
=> Refactor commit pipeline
